#!/bin/bash
set -eu

if [ "${DOCKER_TAG}" = "latest" ]; then
  ICX_VERSION_=$(docker run -t --rm ${IMAGE_NAME} icx --version | grep "oneAPI DPC")
  ICX_VERSION=$(echo ${ICX_VERSION_} | cut -d " " -f5)
  ICX_VERSION_DETAIL=$(echo ${ICX_VERSION_} | cut -d " " -f6 | grep -E -o '[0-9.]+')
 
  docker tag ${IMAGE_NAME} ${DOCKER_REPO}:${ICX_VERSION}
  docker push ${DOCKER_REPO}:${ICX_VERSION}

  docker tag ${IMAGE_NAME} ${DOCKER_REPO}:${ICX_VERSION_DETAIL}
  docker push ${DOCKER_REPO}:${ICX_VERSION_DETAIL}
fi
